name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  push:
    # Master or main branch that you want to trigger this workflow for
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:                                                  
  Fortify-SAST:
    # Use the appropriate runner for building your source code
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Git Bash
        run: choco install git
        shell: cmd

      - name: Test Bash Script
        shell: bash
        run: |
          echo "This is a test sentence written by a Bash script on a Windows runner." > test_output.txt
          cat test_output.txt

      - name: Upload Test Output
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test_output.txt
