name: Fortify ScanCentral SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Fortify-SAST:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Fortify AST Scan
        # You may pin to the exact commit or the version.
        # uses: fortify/github-action@ff40cc3fc263fa6edc64b77fa2486e79a6e32d1b
        uses: fortify/github-action@v1.0.0
        with:
          # Run a SAST scan, takes either true or false (default)
          sast-scan: true # optional, default is false
