name: Fortify ScanCentral SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Fortify-SAST:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Binaries in PATH
        run: |
          Write-Output "Binaries found in the PATH:"
          $pathDirs = $env:PATH -split ';'
          foreach ($dir in $pathDirs) {
            Write-Output "Directory: $dir"
            if (Test-Path $dir -PathType Container) {
              Get-ChildItem $dir
            } else {
              Write-Output "Directory not found."
            }
          }
