name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  push:
    # Master or main branch that you want to trigger this workflow for
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:                                                  
  Fortify-SAST:
    # Use the appropriate runner for building your source code
    runs-on: self-hosted

    steps:
    - name: Test Bash Script
      shell: bash
      run: |
        /C/msys64/usr/bin/bash -c "echo 'This is a test sentence written by a Bash script on a Windows runner.'
