name: Fortify ScanCentral SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Fortify-SAST:
    runs-on: self-hosted
    
    steps:    
    - name: Check out source code
      uses: actions/checkout@v4  
    - name: Run ScanCentral SAST Scan
      uses: fortify/github-action@main
      with:
       sast-scan: true
      env:
        SSC_URL: ${{secrets.SSC_URL}}
        SSC_TOKEN: ${{secrets.SSC_TOKEN}}
        SC_SAST_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
        # EXTRA_SC_SAST_LOGIN_OPTS: --socket-timeout=60s
        SSC_APPVERSION: GitHub SAST Testing:V1
        # EXTRA_PACKAGE_OPTS: -bf custom-pom.xml
        SC_SAST_SENSOR_VERSION: 23.2
        # DO_WAIT: true
        # DO_EXPORT: true
        # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
