name: Fortify ScanCentral SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Fortify-SAST:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Binaries in PATH
        run: |
          echo "Binaries found in the PATH:"
          for dir in $(echo $PATH | tr ":" "\n")
          do
            echo "Directory: $dir"
            if [ -d "$dir" ]; then
              ls "$dir"
            else
              echo "Directory not found."
            fi
          done
