name: Fortify ScanCentral SAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Fortify-SAST:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Directories in PATH
        run: |
          Write-Output "Directories in the PATH:"
          $pathDirs = $env:PATH -split ';'
          foreach ($dir in $pathDirs) {
            Write-Output $dir
          }
