name: Bash Hello World

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Bash Command
        shell: bash
        run: '/c/msys64/usr/bin/bash.exe -c "echo Hello, World!"'
