name: Bash Hello World

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Display the path
        shell: pwsh
        run: echo ${env:PATH}
