name: Bash Hello World

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Set Bash Path
        run: |
          echo "##[set-env name=BASH_PATH]/c/msys64/usr/bin/bash.exe"
      
      - name: Run Bash Command
        shell: bash
        run: |
          ${{ env.BASH_PATH }} -c 'echo "Hello, World!"'
