name: Bash Hello World

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Run Bash Command
        run: |
          '/c/msys64/usr/bin/bash.exe' -c 'echo "Hello, World!"'

