name: List Environment Variables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  list-env-vars:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List environment variables
      run: set
