name: Test SSL Connection

on:
  workflow_dispatch:

jobs:
  test-ssl-connection:
    runs-on: self-hosted
    
    steps:
      - run: echo "Hello World"
      - run: Invoke-WebRequest -Uri "https://btpgcsvm83727/scancentral-ctrl/"
